#!/usr/bin/env python3

from sys import argv
import collections


def build_values(argv):
    if argv[1] == "-limit" and len(argv):
        return " ".join(argv[2:]) if len(argv) > 2 else "Hello World"
    return " ".join(argv[1:]) if len(argv) > 1 else "Hello World"


def arguments():
    Args = collections.namedtuple('args', 'limit values')
    if len(argv) == 1:
        return Args(limit=False, values="Hello World")
    return Args(limit=argv[1] == "-limit", values=build_values(argv))


def main(args):
    if args.limit:
        for i in range(20):
            print(args.values)
    else:
        while True:
            print(args.values)


if __name__ == '__main__':
    main(arguments())

