#!/usr/bin/env python3
import sys, os, json
from typing import List
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__),  '..')))
from Fish.Remote.server import TCPServer

HOST = '127.0.0.1'


def run_server(port: int) -> List[int]:
    server = TCPServer(HOST, port)
    server.configure_server()
    return server.wait_for_client()


def main():
    if len(sys.argv) != 2:
        print("usage: ./xserver int")
        sys.exit(1)

    port = sys.argv[1]

    if not port.isnumeric():
        print("usage: ./xserver int")
        sys.exit(1)

    results = run_server(int(port))
    print(json.dumps(results))


if __name__ == "__main__":
    main()
