#!/usr/bin/env python3

import tkinter as tk
from sys import argv
import matplotlib.path as mplPath
import numpy as np


def inside(point, poly):
    bbPath = mplPath.Path(poly)
    return bbPath.contains_point(point)


def handle_button_press(event, root, size):
    if str(event.type) == 'ButtonPress':
        points = np.array([
            [size, 0],
            [2*size, 0],
            [3*size, size],
            [2 * size, 2 * size],
            [size, 2 * size],
            [0, size]])
        if inside((event.x, event.y), points):
            root.destroy()



def build_points(size):
    points = [size, 2.5,
              2*size, 2.5,
              3*size, size,
              2 * size, 2 * size,
              size, 2 * size,
              0, size]

    return points


def draw(canvas, size):
    points = build_points(size)
    canvas.create_polygon(points, outline="red", fill="white", width=1)


def parse(argv):
    try:
        size_canvas = float(argv[1])
    except ValueError as ve:
        return -1
    return size_canvas if size_canvas > 0 else -1


if __name__ == '__main__':
    root = tk.Tk()
    root.resizable(False, False)
    size = parse(argv)
    if size == -1:
        print("usage: ./xgui positive-integer")
        exit()
    canvas = tk.Canvas(root, width=size*3, height=(size*2))
    draw(canvas, size)
    canvas.pack()
    root.bind('<ButtonPress-1>',
              lambda event: handle_button_press(event, root, size))
    root.mainloop()

